version: '3.9'

services:
  postgres:
    image: postgres:16
    container_name: meu_postgres
    restart: always
    environment:
      POSTGRES_USER: kauedb
      POSTGRES_PASSWORD: kaue12345
      POSTGRES_DB: produtos
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    container_name: meu_pgadmin
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    depends_on:
      - postgres

volumes:
  pgdata:
